version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"   #  interfaz web de Neo4j
      - "7687:7687"   # Pprotocolo bolt (consultas)
    environment:
      - NEO4J_AUTH=neo4j/passwd4 %2fdG  
    volumes:
      - neo4j_data:/data       
      - neo4j_logs:/logs       
      
      
volumes:
  neo4j_data:
  neo4j_logs:
 

